<?php 

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2017
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

/**
 * Attributes
 */
$GLOBALS['TL_LANG']['PCT_CUSTOMELEMENTS']['FILTERS']['multidatespicker'] = array('Datum, Mehrfachauswahl','Filtert Einträge nach gesetztem Datum (positiv) oder schließt die Einträge aus (negativ)');