<?php 

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2017
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

$GLOBALS['TL_LANG']['tl_pct_customelement_filter']['multidatespicker_mode'][0] = 'Modus';
$GLOBALS['TL_LANG']['tl_pct_customelement_filter']['multidatespicker_mode'][1] = 'Wählen sie den Modus des Filters. Additiv: Einträge werden angezeigt, Subtraktiv: Einträge werden ausgeschlossen';
$GLOBALS['TL_LANG']['tl_pct_customelement_filter']['multidatespicker_mode']['add'] = 'Additiv';
$GLOBALS['TL_LANG']['tl_pct_customelement_filter']['multidatespicker_mode']['sub'] = 'Subtraktiv';